apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deploy
  labels:
    app: bankapp-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-app
  template:
    metadata:
      labels:
        app: bankapp-app
    spec:
      containers:
      - name: bankapp-container
        image: shivanggupta998/sh-bankapp:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-np-service
  labels:
    app: bankapp--np-app
spec:
  selector:
    app: bankapp-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8081
    targetPort: 8081
